### ISSUE TITLE
`google` is undefined error

### ISSUE THREAD

**Issue by shunkakinoki** [brunocrosier/google-one-tap#2]
Thanks for this awesome project!!! 🔥🔥🔥

Whenever I try to reproduce the lib, I get a `google` is undefined error.
Anything I can do to avoid this?

**Comment by brunocrosier** [comment]
Hey Shun! Hard to debug that without seeing it, but from that error, I would guess that maybe the google script isn't loading ?

Make sure you have this: 
```javascript
        <script src="https://accounts.google.com/gsi/client" />
```

Also, make sure that you do the initial setup correctly: https://developers.google.com/identity/one-tap/web/guides/get-google-api-clientid

**Comment by shunkakinoki** [comment]
Thanks for the link!
I included without async and defer, and it still gives me the error.
Oh, maybe it's me having to submit for verification. Is your app verified through google?

**Comment by brunocrosier** [comment]
No it isn't verified through Google.

Can you share your code? 

On [this page](https://console.developers.google.com/apis/credentials) have you set everything up correctly ? Have you added a OAuth 2.0 Web Client ?

**Comment by shunkakinoki** [comment]
Thanks for your support!!!
Turns out refactoring to `window.google` solved the problem!!!
(in my typescript configuration, that is)

Thanks for taking your time to help me get through this, and thanks again for this awesome project to showcase google one tap login!

**Comment by brunocrosier** [comment]
Ah, I see what you mean now. Yes, `google` comes from the external script, so it will show as `undefined` in Typescript :) 

I'm glad you found it useful - feel free to show me what you end up building with it! Cheers
